name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/kiii:${{ github.run_number }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/kiii:${{ github.run_number }}

      - name: Update Kubernetes Deployment
        run: |
          sed -i "s|image: .*|image: ${DOCKER_USERNAME}/kiii:${{ github.run_number }}|" kubernetes/flask-deployment.yaml
          git config --global user.email "marin-o.actions@github.com"
          git config --global user.name "marin-o actions"
          git add kubernetes/flask-deployment.yaml
          git commit -m "Update deployment to version ${DOCKER_USERNAME}/kiii:${{ github.run_number }} [skip ci]"
          git push https://${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}

          sleep 10

      - name: Notify on success
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SEND_EMAIL }}
          password: ${{ secrets.SEND_PASSWORD }}
          subject: "Build Success"
          body: "Build and push succeeded!"
          to: ${{ secrets.RECEIVE_EMAIL }}
          from: ${{ secrets.SEND_EMAIL }}

      - name: Notify on failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SEND_EMAIL }}
          password: ${{ secrets.SEND_PASSWORD }}
          subject: "Build Failure"
          body: "Build and push failed!"
          to: ${{ secrets.RECEIVE_EMAIL }}
          from: ${{ secrets.SEND_EMAIL }}
